spring:
    datasource:
        url: jdbc:h2:file:${user.home}\portal\database
        driverClassName: org.h2.Driver
        password: sa
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
server:
    port: 8080